"use client";

import { useCallback, useEffect, useState } from "react";
import { AppShell } from "./AppShell"; import { EmptyState, ErrorState, LoadingSkeleton } from "./AsyncStates";
import { getReport } from "@/lib/api"; import { formatNpr } from "@/lib/formatters"; import type { Report } from "@/lib/types";
import { demoCategoryBreakdown, demoReport, demoSalesForecast } from "@/lib/demoData";
import { BudgetDonut } from "./charts/BudgetDonut"; import { ForecastChart } from "./charts/ForecastChart"; import { ProgressBar } from "./charts/ProgressBar"; import { FinancialDataSource, type FinanceInput } from "./FinancialDataSource";

export function ReportView({ id }: { id: string }) {
  const isDemo = id === "demo"; const [report, setReport] = useState<Report | null>(isDemo ? demoReport : null); const [error, setError] = useState(""); const [loading, setLoading] = useState(!isDemo);
  const load = useCallback(async () => { setLoading(true); try { setReport(await getReport(id)); setError(""); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to load report."); } finally { setLoading(false); } }, [id]);
  useEffect(() => { if (isDemo) return; const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [isDemo, load]);
  if (loading) return <AppShell><LoadingSkeleton rows={5}/></AppShell>;
  if (error) return <AppShell><ErrorState message={error} retry={() => void load()}/><p className="availabilityHint">The report becomes available when the backend workflow reaches the reporting stage.</p></AppShell>;
  if (!report) return <AppShell><EmptyState title="No report yet" message="The report will become available when the workflow reaches the reporting stage."/></AppShell>;
  const forecast = isDemo ? demoSalesForecast : [{month:"Current",historical:report.sales_prediction.current_sales},{month:"Predicted",forecast:report.sales_prediction.predicted_sales}];
  function applyFinance(data:FinanceInput){if(!isDemo)return;setReport(current=>current?{...current,financial:{total_budget:data.totalBudget,planned_spend:data.actualSpend,remaining_budget:data.totalBudget-data.actualSpend},sales_prediction:{...current.sales_prediction,current_sales:data.sales}}:current)}
  return <AppShell mode={isDemo ? "demo" : "real"}><header className="pageTitle"><div><span>Workflow {id}</span><h1>Financial Intelligence</h1><p>Q3 budget utilization and sales forecasting.</p></div><div className="reportActions"><FinancialDataSource demo={isDemo} onApply={applyFinance}/><button className="secondaryButton">⇩ Export PDF</button></div></header><section className="kpiGrid"><article><span>Total budget</span><strong>{formatNpr(report.financial.total_budget)}</strong></article><article><span>Planned spend</span><strong>{formatNpr(report.financial.planned_spend)}</strong></article><article><span>Remaining budget</span><strong>{formatNpr(report.financial.remaining_budget)}</strong></article><article><span>Predicted growth</span><strong>{report.sales_prediction.growth_percent.toFixed(1)}%</strong></article></section><div className="reportGrid"><aside className="utilizationCard"><span>Total Budget Utilization</span><BudgetDonut used={report.financial.planned_spend} total={report.financial.total_budget}/><dl><div><dt>Current Sales</dt><dd>{formatNpr(report.sales_prediction.current_sales)}</dd></div><div><dt>Predicted Sales</dt><dd>{formatNpr(report.sales_prediction.predicted_sales)}</dd></div></dl>{isDemo&&<section className="categoryBreakdown"><h3>Category Breakdown</h3>{demoCategoryBreakdown.map(item=><article key={item.name}><div><span>{item.name}</span><strong>{item.value}%</strong></div><ProgressBar value={item.value}/></article>)}</section>}</aside><section className="chartCard"><header><div><span>Sales Revenue Forecast</span><h2>{formatNpr(report.sales_prediction.predicted_sales)}</h2></div><small>Method: {report.sales_prediction.method.replaceAll("_", " ")}</small></header><ForecastChart data={forecast}/></section></div><aside className="insightsCard reportInsights"><section><h2>Risks</h2>{report.risks.length ? <ul>{report.risks.map((item) => <li key={item}>{item}</li>)}</ul> : <p>No risks were returned.</p>}</section><section><h2>AI Business Insight &amp; Recommendation</h2>{report.recommendations.length ? <ul>{report.recommendations.map((item) => <li key={item}>{item}</li>)}</ul> : <p>No recommendations were returned.</p>}</section></aside></AppShell>;
}
