"use client";

import { useCallback, useEffect, useState } from "react";
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { AppShell } from "./AppShell"; import { EmptyState, ErrorState, LoadingSkeleton } from "./AsyncStates";
import { getReport } from "@/lib/api"; import { formatNpr } from "@/lib/formatters"; import type { Report } from "@/lib/types";

export function ReportView({ id }: { id: string }) {
  const [report, setReport] = useState<Report | null>(null); const [error, setError] = useState(""); const [loading, setLoading] = useState(true);
  const load = useCallback(async () => { setLoading(true); try { setReport(await getReport(id)); setError(""); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to load report."); } finally { setLoading(false); } }, [id]);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [load]);
  if (loading) return <AppShell><LoadingSkeleton rows={5}/></AppShell>;
  if (error) return <AppShell><ErrorState message={error} retry={() => void load()}/><p className="availabilityHint">The report becomes available when the backend workflow reaches the reporting stage.</p></AppShell>;
  if (!report) return <AppShell><EmptyState title="No report yet" message="The report will become available when the workflow reaches the reporting stage."/></AppShell>;
  const comparison = [{ name: "Current", sales: report.sales_prediction.current_sales }, { name: "Predicted", sales: report.sales_prediction.predicted_sales }];
  return <AppShell><header className="pageTitle"><div><span>Workflow {id}</span><h1>Financial Intelligence</h1><p>Budget utilization and sales prediction generated by the reporting service.</p></div></header><section className="kpiGrid"><article><span>Total budget</span><strong>{formatNpr(report.financial.total_budget)}</strong></article><article><span>Planned spend</span><strong>{formatNpr(report.financial.planned_spend)}</strong></article><article><span>Remaining budget</span><strong>{formatNpr(report.financial.remaining_budget)}</strong></article><article><span>Predicted growth</span><strong>{report.sales_prediction.growth_percent.toFixed(1)}%</strong></article></section><div className="reportGrid"><section className="chartCard"><header><div><span>Sales Prediction</span><h2>Current vs. predicted sales</h2></div><small>Method: {report.sales_prediction.method.replaceAll("_", " ")}</small></header><div className="chartWrap"><ResponsiveContainer width="100%" height="100%"><BarChart data={comparison}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="name"/><YAxis tickFormatter={(value) => new Intl.NumberFormat("en", { notation: "compact" }).format(value)}/><Tooltip formatter={(value) => formatNpr(Number(value))}/><Bar dataKey="sales" fill="#2563eb" radius={[8,8,0,0]}/></BarChart></ResponsiveContainer></div></section><aside className="insightsCard"><section><h2>Risks</h2>{report.risks.length ? <ul>{report.risks.map((item) => <li key={item}>{item}</li>)}</ul> : <p>No risks were returned.</p>}</section><section><h2>Recommendations</h2>{report.recommendations.length ? <ul>{report.recommendations.map((item) => <li key={item}>{item}</li>)}</ul> : <p>No recommendations were returned.</p>}</section></aside></div></AppShell>;
}
