"use client";

import { useCallback, useEffect, useState } from "react";
import { getWatcherStatus } from "@/lib/api"; import { formatDateTime } from "@/lib/formatters"; import type { WatcherStatus } from "@/lib/types"; import { EmptyState, ErrorState, LoadingSkeleton } from "./AsyncStates";
import { demoComponentHealth, demoWatcherStatus } from "@/lib/demoData";

export function WatcherPanel({ demo = false }: { demo?: boolean }) {
  const [watcher, setWatcher] = useState<WatcherStatus | null>(demo ? demoWatcherStatus : null); const [error, setError] = useState(""); const [loading, setLoading] = useState(!demo);
  const load = useCallback(async () => { try { setWatcher(await getWatcherStatus()); setError(""); } catch (reason) { setError(reason instanceof Error ? reason.message : "Watcher unavailable."); } finally { setLoading(false); } }, []);
  useEffect(() => { if (demo) return; const initial = window.setTimeout(() => void load(), 0); const timer = window.setInterval(() => void load(), 4000); return () => { window.clearTimeout(initial); window.clearInterval(timer); }; }, [demo, load]);
  if (loading) return <LoadingSkeleton rows={5}/>; if (error && !watcher) return <ErrorState message={error} retry={() => void load()}/>; if (!watcher) return null;
  return <div className="watcherView">{error && <p className="inlineError" role="alert">Latest refresh failed: {error}</p>}<section className={`systemBanner ${watcher.state.toLowerCase()}`}><div><span>System status</span><h2>{watcher.state === "IDLE" ? "ALL SYSTEMS OPERATIONAL" : "WATCHER ACTIVE"}</h2><p>{watcher.state === "IDLE" ? "No active recovery operation." : "The Watcher is monitoring an active incident."}</p></div><div><strong>{watcher.active_incidents}</strong><span>Active incidents</span></div></section>{demo && <section className="healthGrid">{demoComponentHealth.map((item) => <article key={item.name}><span>{item.name}</span><strong>{item.value}</strong><small className={item.tone}>{item.tone}</small></article>)}</section>}<section className="eventLog"><header><div><span>Watcher activity</span><h2>System Event Log</h2></div><small>{demo ? "Prototype events" : "Updates every 4 seconds"}</small></header>{watcher.events.length ? <div className="eventTableWrap"><table><thead><tr><th>Timestamp</th><th>Workflow</th><th>Component</th><th>Event</th><th>Retry</th><th>Status</th><th>Message</th></tr></thead><tbody>{watcher.events.map((event, index) => <tr key={`${event.created_at}-${index}`}><td>{formatDateTime(event.created_at)}</td><td>{event.workflow_id ?? "System"}</td><td>{event.component}</td><td>{event.event_type}</td><td>{event.retry_count}</td><td><span className={`eventStatus ${event.resolved ? "resolved" : "open"}`}>{event.resolved ? "Resolved" : "Open"}</span></td><td>{event.message}</td></tr>)}</tbody></table></div> : <EmptyState title="No system incidents" message="No system incidents have been recorded."/>}</section></div>;
}
